### ISSUE TITLE
Insert laws’ full text with the rendering engine

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#198]
At present, the internal XML API generates and stores the full text via a simple concatenation of subsections and their prefixes, wrapping each in paragraph tags:

``` php
$code->text .= '<p>'.(string) $subsection['prefix'].' '.trim((string) $subsection).'</p>';
```

This is not the proper way to handle this. Instead, wait to insert the full text until after the subsections have all been inserted, by iterating through all of the laws and rendering the text, using the same methods that are used within the API and on the public-facing page. That will ensure complete parity between the two.

**Comment by krues8dr** [comment]
Is this still a problem? This entire stretch of code has been entirely rewritten (several times) so I don't know if this is still an issue anymore, and I can't tell from the description what the original issue was by comparison.

**Comment by krues8dr** [comment]
We're now using the raw HTML from the XML so this is a non-issue.
