### ISSUE TITLE
Create a CourtListener interface

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#245]
[CourtListener](http://www.courtlistener.com/) is starting to add state Supreme Court decisions to their offerings, and intends to add all fifty states. Consequently, it is sensible to bake support for it into The State Decoded.

The trick is that CourtListener has no API, and even their bulk downloads are awkward. (They're broken up by year, with no indication of the span of years for which coverage is offered. So to get all court decisions for, say, Indiana, one would need to request 2013, 2012, 2011, etc., until finally a 404 was returned. And that's assuming that there's no year-long gaps in coverage.) So supporting CourtListener really means writing a system to periodically download their bulk files, parse their XML format, store those decisions, index them, put an API on top of all that, and then add support to The State Decoded to interface with that API.

This may reasonably be a separate project—surely it has more utility than for The State Decoded, and I'm not sure that I'd want it tightly coupled, anyway.

**Comment by waldoj** [comment]
The diff for that commit reports lots of changes, but that's just a GitHub bug. All I really did was store an empty variable when CourtListener returns no results, and modify `class.Law.inc.php` to look for empty data and decline to display it.

**Comment by waldoj** [comment]
To be clear, the only thing that's left to be done here is [expiring cached data](#issuecomment-28417655).

**Comment by waldoj** [comment]
Looks like f4ec8c5150e253a3a7cfbd5b6fe071c329f34d2e didn't go far enough to caching that there are no results. Best to remove the variable entirely, within `Law::get_law()`.

**Comment by waldoj** [comment]
All that remains on this issue is to remove old data from the cache periodically (allowing new data to be loaded from CourtListener). "Old" can reasonably be determined using the creation time field in the metadata table. Since the definition of "periodically" will vary between implementations, that should involve a new config setting. The catch is the question of what triggers that removal. Requiring people to create a crontab entry isn't good. My best idea is to run that cleanup process at the time that an import is run. The downside of this is that a code may reasonably only be updated annually, but only updating court records annually doesn't seem great.

Maybe we give people a button to do this, in the admin section, also ensure that it can be done via the command line tool, and also do it at the time that an import is run? That way there's a manual option, savvy folks can automate it via cron, _and_ it'll be done at import time?

**Comment by krues8dr** [comment]
If they're running an update on an existing code, doesn't this already blow away the old metadata and thus clear the cache?

**Comment by krues8dr** [comment]
Rather, statement: updating an existing code blows away old metadata thus clearing the cache here. So does anything need doing?

**Comment by krues8dr** [comment]
We could add a function to delete metadata by key via the command line tool, but that seems odd for some reason.  I need to think about that part more.

**Comment by waldoj** [comment]
It only blows away the old metadata if they're dumping the old edition (AFAIK). Court decisions are happening constantly, so a legal code that's only updated every year or two can't have the court decisions updated only every year or two.

**Comment by krues8dr** [comment]
So what should happen to this metadata on old (not-current) editions? The laws_meta table currently keys on the law's `id`, not the section number, so it's edition-specific already – do we need non-edition-specific metadata instead?

**Comment by waldoj** [comment]
Hmm. I hope we're not hitting CourtListener for every version of a law...but we might be? I don't mind never expiring CourtListener metadata on old editions, because they are, after all, old editions—one doesn't expect them to be current. I also don't mind clearing out CourtListener metadata for old editions, because I think it's fine for old editions not to list court rulings, because they're bound to sometimes include court rulings that are more recent than that edition, which would be confusing.

Seems like it might be wise to blow away CourtListener metadata for old rulings, and prevent querying CourtListener's API for anything other than the current edition.

**Comment by krues8dr** [comment]
With that PR, I've added metadata-clearing for *all* court data if you're importing data for the current edition.

I've also created a command to clear out metadata, per edition and/or field.  It looks like this:

```
./statedecoded clearmetadata --edition=vacode --field=court_decisions
```

**Comment by krues8dr** [comment]
Also, I noticed that CourtListener is returning results that I'm not expecting, I dunno if this is an API change or what.  For instance, the query on `§ 8.01-27` is: 

```
https://www.courtlistener.com/api/rest/v3/search/?q=%228.01-27%22&court=ca4,vaeb,vawb,vaed,vawd,va,vactapp&order_by=score+desc&format=json
```

And that returns a couple of cases about Durham, NC.  @mlissner, is that correct?  I haven't touched this stuff much, so it's likely a `pibcak` error.

**Comment by mlissner** [comment]
Looks like you're filtering to include CA4 cases, which would include NC. Seems right to me?

**Comment by krues8dr** [comment]
![closeenough](https://cloud.githubusercontent.com/assets/127904/25065763/28a94460-21e3-11e7-8b5f-97796e9846c9.png)

**Comment by waldoj** [comment]
I think this is wrapped up, then, @krues8dr?

**Comment by mlissner** [comment]
Yay! Now, then, to release v4 of the API.....

(KIDDING!)

**Comment by krues8dr** [comment]
![corgi-fail](https://cloud.githubusercontent.com/assets/127904/25287359/0f33f466-268f-11e7-9867-f132c7e74417.gif)
