### ISSUE TITLE
Provide an option more specific than "empty database"

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#256]
When working on getting an import to work properly, it's often necessary to repeatedly clear the database and re-import. That's going to be problematic for folks importing new years, while wanting to retain prior years' data. Provide a middle option, and emphasize it, since it's almost certainly what people actually want.

This is a child issue of #125 ("Make the admin section interactive and functional").

**Comment by krues8dr** [comment]
This is now complete on the `edition-update` branch.
