### ISSUE TITLE
Fix wrapping section numbers in law listings

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#307]
When the section number is too long to fit in the left column on a law listing, it breaks and occupies a second line. This throws off the layout and the float of the next law, resulting in them stacking up:

![wrap](https://f.cloud.github.com/assets/656758/620779/c79a59a8-ceed-11e2-8797-d8e88174f494.png)

I've seen it cascade when there's a series of long section numbers, and it's rather a mess.

It seems to me that the ideal solution would be one that would allow that left column to collectively flex, to expand to the width of the widest section number in the list. But I appreciate that might be impractical, in which case a decent backup option would be to have the list handle more gracefully when that text wraps (just as when laws' catch lines are too long, which works great). And, of course, there's always the option of simply making that first column wider, but I don't know that we want to make every code's layout based on the longest possible section number in any legal code that we can find. :)

**Comment by krues8dr** [comment]
It's back with a vengeance.  I tried upping the margin width to 150px but it's still not enough.  We might want to make this a *gasp* table. 

http://chicagocode.org/18/

**Comment by waldoj** [comment]
It was a good run.

**Comment by waldoj** [comment]
_grumble grumble_

No, you're right. Table it is.

**Comment by krues8dr** [comment]
![screen shot 2015-03-11 at 4 44 16 pm](https://cloud.githubusercontent.com/assets/127904/6606433/f4b69a62-c80d-11e4-81fb-6556b5cee29a.jpg)

Pics or it didn't happen.

**Comment by krues8dr** [comment]
Also, look it's #574 happening too.

**Comment by waldoj** [comment]
For the record, I do _much prefer_ providing this data as a definition list, semantically, but there's a point when you've just got to be realistic. The fact is that there's bulk data and an API—nobody needs to be scraping these records. This isn't really tabular data, but it's not _not_ tabular data. Tables are such a sensible solution that I think it's the way to go.
