### ISSUE TITLE
Improve the display of laws with limited sidebar data

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#321]
Laws with limited information look odd in the widest display. In the second-widest display, this looks fine:

![sidebar-normal](https://f.cloud.github.com/assets/656758/645190/6dc5ad90-d39f-11e2-964a-df32bdf79b26.png)

But in the widest display, it looks like this:

![sidebar-narrow](https://f.cloud.github.com/assets/656758/645192/72acf1c4-d39f-11e2-9e99-1c4529f74bfe.png)

If there were other columns, that might be sensible, but with just one, it's just weird. Perhaps I can provide a variable in PHP that indicates how many columns worth of data that there are? Then the appropriate style can be applied (e.g, `aside#sidebar section.related-group.2` vs `aside#sidebar section.related-group.1`).

**Comment by krues8dr** [comment]
Just poking back in to say there are still issues with this.  @cmbirk has reported this again on ChicagoCode, but I'm seeing it even on vacode.  E.g.  https://vacode.org/4.1-300/

**Comment by krues8dr** [comment]
This should be resolved with #567 #676
