### ISSUE TITLE
Review the code that generates structural unit statistics

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#335]
Review the changes committed for #247—that's the code that calculates and stores statistics about structural units. I wrote that in haste, without my head in the right place, and it's going to benefit from a review.

**Comment by krues8dr** [comment]
What needs to be done here?

**Comment by waldoj** [comment]
You know how sometimes your head isn't in the game, so you're just randomly writing code and reloading the page to see if it works? And sometimes, by some amazing coincidence—like infinite monkeys pounding on typewriters—you produce something that seems to work? [This commit was written like that](https://github.com/statedecoded/statedecoded/commit/b2df4d4c3f34c2fa2d1fa024c6d8702da5da15e1). It "worked," in the sense that I expected it to produce output X and it produced output X, but I didn't test it adequately to know if sometimes it also produces output Y or output Z. If you could just read through the code and make sure it's sensible, that's all that's required here.

Looking at it now, I wonder about [this iterator](https://github.com/statedecoded/statedecoded/commit/b2df4d4c3f34c2fa2d1fa024c6d8702da5da15e1#diff-a07d6e2ef4c21323fee02f9c1aa13578R663)—how the heck does `$this->stats` contain _anything,_ given that I just created an instance of it 17 lines previously?

Generally, everything in this looks OK to me, but doing my own code review—even four years later—feels like editing my own writing. :)

**Comment by krues8dr** [comment]
Well, my bigger question is, why do we need this code at all?  We already are querying the child section and structure information when we display the parent structure – this information doesn't appear to be used outside of the `structure.php` page to display this.

**Comment by waldoj** [comment]
Well, [when I created this functionality](https://github.com/statedecoded/statedecoded/issues/247#issue-11675251), I wrote:
> That makes possible text like "this article is divided into 32 chapters, each of which contain 2–16 laws, comprised of 257 laws in all." This will help people to get their bearings and understand how much material lies out of sight.
I still think that's true. When looking at the contents of a structural unit, it's impossible to know how much is under the surface. This is a not-terrible method of providing that information.

**Comment by krues8dr** [comment]
This looks like it's working to me.  The text display on the frontend has ended up with some weird paragraphing due to tables for the lists, so I'm breaking that up a little bit more.  This results in the `It’s comprised of the following # sections.` sentence being on a separate line, but that's better than having to deal with weirdness when we have both sections and structures as children of a structure (which I have on a few city codes).
