### ISSUE TITLE
Establish a method of viewing old versions of a law

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#362]
This issue is two-part:

1. Define the URL structure by which old versions will be identified.
1. Create the interface to actually display those, and to indicate when one is viewing an old version.

I'm strongly tempted to do this with URL fragments, e.g. `http://code.example.org/1.23-45.6/#2011`. What appears after the fragment is the unique identifier for the edition in which it appears, from the `editions` table. The only scenario in which this would be problematic is if the edition identifier is coincidentally the same as a subsection identifier URL fragment, leading to anchor confusion. That strikes me as unlikely, since edition identifiers are very likely to be time-bound, whether years, years and months, or years months and days.

The alternatives seem to consist of a) `http://code.example.org/1.23-45.6/2011/` or b) `http://code.example.org/2011/1.23-45.6`. The former isn't terrible, but it strikes me as semantically inferior. The latter is actively bad, because it either creates an inconsistent URL structure or unnecessarily complicates all URLs by requiring the insertion of a year.

Turning to the interface to look at old versions, I think this might be good cause to use a slider. Left is older, right is newer. How that works on a touch device is unclear to me, but I think HTML5 wound up with a slider element, so if we could just use that, then this is a problem for the browser makers to deal with or have already dealt with.

**Comment by krues8dr** [comment]
This is now complete on the `edition-update` branch.

**Comment by krues8dr** [comment]
Considering the size and complexity of the editions update, once these last few tickets are complete, I would propose we mark it as a 0.9 release?  @waldoj any thoughts?

**Comment by waldoj** [comment]
You know my feelings on the matter: :shipit:
