### ISSUE TITLE
Create a method of populating or managing the editions table

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#382]
When adding new versions of editions, or managing a just-imported edition, we need to provide a mechanism for setting the names of those editions, as will appear in URL slugs and navigation elements. Of course, this must be compatible with #362 ("Establish a method of viewing old versions of a law").

We'll need to limit the labels for editions to URL-viable descriptors. I suggest all lowercase, no spaces. By allowing something other than years, we're going to have to start URL encoding it when output within a URL.

**Comment by krues8dr** [comment]
This is now complete on the `edition-update` branch.
