### ISSUE TITLE
Figure out how to handle Solr's section number tokenizer

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#425]
In Solr's `schema.xml`, there's [a section number tokenizer](https://github.com/statedecoded/statedecoded/blob/UI/solr_home/statedecoded/conf/schema.xml#L342). _This isn't universalizable_. Figure out how to handle the modification of this based on information already provided in `config.inc.php`. Also, figure out what the tokenizer does—that is, what the impact is of leaving it as-is, and how important it is to have to accommodate different section number structures.

**Comment by krues8dr** [comment]
This now splits on hyphens or periods, which appears to work, for most of the cases I've encountered.  I've updated the documentation to match.
