### ISSUE TITLE
Explain how to add a new page

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#428]
Specifically, how to modify `routes.inc.php` to accomplish that.

**Comment by waldoj** [comment]
@krues8dr, this is as simple as:
```php
$router->addRoute('contact', '^/contact(/.*)?$', 'contact.php');
```
Right? I just want a sanity check before I write this up.

**Comment by krues8dr** [comment]
Yup, and to use the template engine that's built-in, a minimal page would look like:

```
/*
 * Create a container for our content.
 */
$content = new Content();

$body = 'Hello World';

/*
 * Put the shorthand $body variable into its proper place.
 */
$content->set('body', $body);

/*
 * Parse the template, which is a shortcut for a few steps that culminate in sending the content
 * to the browser.
 */
$template = Template::create();
$template->parse($content);
```

You can also just *not* use the router and create a real file (either .php or .html) and refer to it by the usual path (e.g. `/contact.html`);
