### ISSUE TITLE
Run XML through a linter before passing it to Solr

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#433]
Solr has absolutely no tolerance for XML errors. So we need a method of linting all of the XML and creating a blacklist of files with errors. We already have the functionality in `ParserController::index_laws()` to apply a blacklist, and it works fine, we just need to *generate* that blacklist.

I'm thinking `xmllint`. Specifically, `xmllint --noout *`. Its output isn't totally pure, but I think we can use a regex to extract all of the XML filenames from that list, unique it, and then use that as our blacklist. But I think we'll need to see how common `xmllint` is. It looks like it's easily installed (e.g., `sudo apt-get install libxml2-utils` on Ubuntu), but that's going to require more research.

**Comment by krues8dr** [comment]
We're no longer feeding XML into Solr so this doesn't matter anyway.  I'll keep this open if we want to post-process our XML generation (in which case we should rename the ticket), but otherwise this is no longer an issue.

**Comment by waldoj** [comment]
Well, since Solr is still an option for folks, and since Solr seizes up and dies if there's a single XML error, I think it's best to retain. After I put hours and hours into work into this damned problem, I'll just add in those two lines, test it, and be done with it. :)

**Comment by krues8dr** [comment]
Nono, we're using Solarium, not ingesting XML.  So this isn't relevant anymore.

**Comment by waldoj** [comment]
I missed this memo. Huzzah!
