### ISSUE TITLE
Use a safer character for storing laws' structures in Solr

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#440]
At present, when Solr indexes laws, it stores their structural ancestries as a single string, with `/` separating each structure's name. For example: `Agriculture, Animal Care, and Food/Milk, Milk Products, and Dairies`. This will yield inaccurate breadcrumb trails when displaying search results for laws that are descendants of structural units that contain slashes in their title. I believe that's the only problem, at present, with using slashes.

In Virginia, two chapters are affected, "Fire/EMS Departments and Fire/EMS Companies" and "State/Local Hospitalization Program." Of course, there are liable to be a great many structural units and laws affected in other legal codes.

Because of the difficulty of fixing this (or, rather, my lack of knowledge about what intra-Solr ramifications that there might be to modifying this), along with its de minimis impact, I'm assigning this to the "Future" milestone.

**Comment by krues8dr** [comment]
Per 441, just querying the database for structure info.
