### ISSUE TITLE
Make search results' ancestries into links

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#441]
We display the structural ancestry of each law in the search results as a breadcrumb trail, at the bottom of the result, but those structures aren't clickable:

![results](https://f.cloud.github.com/assets/656758/1284132/2b20e822-2f90-11e3-97d7-06a4eee1c22a.png)

In the above, it's "Taxation" and "Intangible Property Tax" that should be links. They're not links right now because the data is displayed straight from Solr, which stores the text of the structural units, but no further data.

What we'll probably want to do is ignore that data from Solr (thus also solving #440), and instead query the database for each result, in order to get the structural information. That'll give us proper links.

**Comment by krues8dr** [comment]
>What we'll probably want to do is ignore that data from Solr (thus also solving #440), and instead query the database for each result, in order to get the structural information. That'll give us proper links.

Doing that now.
