### ISSUE TITLE
Keyboard guide overlay UI inconsistency

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#471]
The "close" button on the keyboard guide overlay has gotten goofy for some reason. It looks like this when moused over:

![keyboard_guide](https://f.cloud.github.com/assets/656758/1328971/1b5e3844-350e-11e3-8263-1354debb2635.png)

Fix it.

**Comment by krues8dr** [comment]
Made one tweak where scrollbars were appearing and otherwise this looks 👍
