### ISSUE TITLE
Clean up before re-importing an edition

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#499]
When updating a given edition, delete all structures, laws, permalinks, etc that are associated with that edition before importing, as that is presently not being done.

The catch is that we need to be able to roll that back, in case the import fails, or so it seems to me. Somebody would be rightly frustrated to update their edition, hit a deal-breaking error with the data, and find that their site was now devoid of data.

**Comment by krues8dr** [comment]
This is now complete.
