### ISSUE TITLE
Allow downloading of the entire code, sections of code, and chapters of code, in EPUB, Word, and PDF formats

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#50]
There are two promising potential methods of providing EPUB files: [ePubExport](http://sourceforge.net/projects/epubexport/) and "[EPub](http://www.phpclasses.org/package/6115-PHP-Create-ebook-in-EPUB-format-for-ex-Apple-iPad.html)". The former is a MediaWiki extension, the latter a PHP class. Elmer Masters took the "EPub" class and improved upon it for [Free Law Reporter](https://github.com/emasters/Free-Law-Reporter), specifically found [here](https://github.com/emasters/Free-Law-Reporter/blob/master/includes/EPub.php).

**Comment by krues8dr** [comment]
Ok, the hard part of this is done – I've refactored the entire export process into a plugin-based system to generate files. This will make creating new export types much, much easier.  Now all that remains is to use this to generate the new file types.  The generation of the all-in-one files should happen in the new `finishExport` event.
  
Here's the branch:

https://github.com/statedecoded/statedecoded/tree/export-refactor

**Comment by krues8dr** [comment]
That should be the bulk of the work for generating exports.  Most of the new formats rely on `pandoc` to do the lifting from HTML.  PDF is *REALLY* slow, so I don't recommend that for most people.  It also requires some hurdles to get `pdflatex` installed.  

The only thing left here is adding new hooks to the plugins to show the download links dynamically on the relevant pages.

**Comment by waldoj** [comment]
This is great! Presumably we should hold off on merging this branch until those hooks are included?

**Comment by krues8dr** [comment]
Yup!  Hoping to get to that today/this weekend.
