### ISSUE TITLE
Handle editions within Solr

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#500]
At present, Solr is never cleared out. Each new edition just adds more data to it. This might result in having multiple copies of each law show up in search results, or it might overwrite existing records (I'm not sure which). Overwriting existing records might sound OK, but if § 1-2.34-56 is removed from a new edition of the code, it will stay in the index, resulting in people being shown no-longer-extant laws as if they're still on the books.

Realistically, there are three steps to this:

1. Clear out Solr at the same time as clearing out everything else in the database.
1. Establish a field and facet for editions within Solr (which I don't think exists now).
1. Clear out just the edition in question from Solr, rather than everything, when updating an edition.

I'm OK with only doing the first step for v1.0, and saving 2 and 3 for v1.1.

**Comment by krues8dr** [comment]
Just did a lot of this work, attributed to #556.  

I've got a toehold on this now, at least.  The big change here is we're no longer feeding in our existing XML files, we're using Solarium to build up an XML query instead. Almost done here on the backend, I still need to tweak the schema to allow a custom identifier for each site in an all-sites-in-one-core setup, but that's trivial.  And then, of course, making this work on the frontend search again after I've broken it so horribly.

Everything is in place for doing #546 and #441 here too.

**Comment by waldoj** [comment]
That's a heck of an interesting change. It never would have occurred to me!

**Comment by krues8dr** [comment]
There's a regression in this somewhere that broke section numbers and the structure hierarchy in results.

**Comment by krues8dr** [comment]
This is getting pretty close.  I still need to get the frontend search form working with the backend changes I've made here - particularly in handling the edition id that's passed now, but otherwise editions are pretty much working with Solr.  The schema has changed a *lot* though, everything will need to be reindexed.

**Comment by krues8dr** [comment]
This is now complete.
