### ISSUE TITLE
Prev/next being offset vertically

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#518]
This is on SD 0.81, as seen on [Virginia § 2.2-3704](http://vacode.org/2.2-3704/), in Chrome, though the same problem exists in Firefox.

![prev-next](https://f.cloud.github.com/assets/656758/1679379/77d8b69a-5d4e-11e3-88a3-6876d9d23c6f.png)

**Comment by krues8dr** [comment]
CSS appears to have caught up, this is now working.
