### ISSUE TITLE
laws_references shouldn't use section_number as the relational key.

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#542]
Section Numbers may be duplicated, so this is problematic.  It should probably use either the permalink or the record's id.

**Comment by krues8dr** [comment]
Ok let's get back to this, this is a hard one.  Here are a few ideas on the topic, which I don't think are necessarily dependent on each other.

I've got a crazy idea here, and you let me know if it doesn't make sense.  Instead of using a simple regex, why don't we loop over every law in the database, and look for each in turn with a targetted regex - something like `/§ ?:number:/` where we replace `:number:` with every law in turn?  That way we don't get any false negatives.  We then add a row in `laws_references` for every match.

The second part of this is, on the display side if we have multiple references, we can show a popup (similar to our dictionary popup) telling the user that the reference may refer to 1,2, or 3.  They can probably figure out which one from the title there, even if we can't.  

(This in particular also starts to flesh out the experience of allowing short urls on sites with duplicate numbering, because we can show a page listing all matches in that case - though we'll obviously need to use long urls for traversing the code by browsing.)

Since we already have `law_id`, `target_law_id`, and `edition_id`, this should be easy otherwise.

**Comment by waldoj** [comment]
So you're saying we'd step through every law (e.g,. §§ 1-1, 1-2, 1-3, etc.) and search the _entire_ code for each of them in turn? I'm not sure what the advantage of that is, other than not getting any false positives (e.g., the phrase "up to 3-4 persons" matching the regex, even though no § 3-4 exists), but false positives aren't such a big deal—we weed them out with a single SQL query that takes less than a second. The downside would seem to be that it'd be a whole lot slower. So what's gained by this approach?

It seems to me like your UI idea works with the current setup, doesn't it? (Which, BTW, seems like an wholly reasonable way to handle non-unique section numbers.)

**Comment by krues8dr** [comment]
I'll move ahead with the UI piece then, I don't think I've thought through the other part enough yet and it's too late for me to be doing any heavy thinking. ;)

**Comment by krues8dr** [comment]
@waldoj Should [this](https://github.com/statedecoded/statedecoded/blob/master/includes/class.State-sample.inc.php#L2105) be setting `mentions=mentions+1` on duplicate key?  I'm not sure how mentions work.

**Comment by waldoj** [comment]
Nope. `ON DUPLICATE KEY` requires that _something_ be updated if there's a collision. There's no `ON DUPLICATE KEY DO NOTHING` OPTION. So I just arbitrarily chose `mention` as the field to update to its existing value.

**Comment by krues8dr** [comment]
Gotcha.

**Comment by krues8dr** [comment]
How does this reference popup look, for handling instances where we have multiple laws sharing the same section number?

![screen shot 2015-05-06 at 10 52 48 pm](https://cloud.githubusercontent.com/assets/127904/7507762/bdfdee42-f442-11e4-9b95-34fc98dddf27.jpg)

**Comment by waldoj** [comment]
Makes sense to me!

**Comment by krues8dr** [comment]
Great. Since that's only in the Javascript, we need a way for screen readers to be able to see that content.  I think the best way to do this is add footnotes at the bottom of the page with this same text appended, visible only to screen readers.  I'll add `<sup>` links that are similarly invisible to normal users as well.  (Though this might be useful for *all* users, too?  What do you think?)

**Comment by waldoj** [comment]
I'm disinclined to display it to all users, because I suspect that most users are quite unlikely to click any given reference to need to know that it resolves to multiple places. I think it adds an unnecessary level of complexity to the display, especially since superscripted footnotes are the epitome of "this thing I'm reading is over my head" for many people.

**Comment by krues8dr** [comment]
Ok, if you're using a screen reader, you'll "see" this:

![screen shot 2015-05-09 at 12 53 56 pm](https://cloud.githubusercontent.com/assets/127904/7551105/ba46eda8-f64a-11e4-9615-1df00e0a93a7.jpg)

And if you're not, it looks normal:

![screen shot 2015-05-09 at 12 54 11 pm](https://cloud.githubusercontent.com/assets/127904/7551107/c42d74e0-f64a-11e4-8e39-e3fcbe83170a.jpg)

**Comment by waldoj** [comment]
This is very clever!
