### ISSUE TITLE
Allow search by structure as well as content

### ISSUE THREAD

**Issue by leilis** [statedecoded/statedecoded#543]
There is a section of the DC Code entitled "Codification and Publication of Acts, Resolutions, Rules, and Orders" (http://dcdecoded.org/I/2/6/). However, it is difficult to find via search, because the term "codification" does not appear in the content of the law, only in the title.  It would be helpful to be able to search by terms both in titles and content.

**Comment by waldoj** [comment]
@krues8dr, am I right in my conclusion that MySQL search interface that you created doesn't address this? ([The hardcoded `FROM laws`](https://github.com/statedecoded/statedecoded/blob/edition-update/includes/class.SqlSearchEngine.inc.php#L238) seems like a giveaway. :)
