### ISSUE TITLE
PHP 5.3 EOL

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#545]
[PHP has announced EOL for *5.3*](http://php.net/index.php#id2014-08-14-1), and we're still supporting 5.2.  Should we up our requirements to account for the lack of security patches?  This also opens up a whole new world of libraries we can use, since 5.4 is a major turning point.

**Comment by krues8dr** [comment]
Well now 5.4 *and* 5.5 are EOL.  5.5 is only in security patches for 6 more months!

http://php.net/supported-versions.php

**Comment by krues8dr** [comment]
FWIW, we should probably start thinking about the transition to PHP 7.  When we do that, we should probably consider running the [PSR Fixer](http://cs.sensiolabs.org/) on everything too, to meet current standards for formatting.  Though we still need to do a bunch of work to meet things like the [Autoloader standards](http://www.php-fig.org/psr/psr-4/) etc.

**Comment by waldoj** [comment]
I've never even _seen_ PHP 7, and don't have the foggiest idea of what's different about it. ¯\\\_(ツ)\_/¯

**Comment by krues8dr** [comment]
http://php.net/manual/en/migration70.php :p
