### ISSUE TITLE
[edition-update branch] Error on admin page.

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#560]
per @waldoj : https://github.com/statedecoded/statedecoded/issues/532#issuecomment-65530664

I'm not seeing this on my local  copy atm, but I'll pull a clean copy tonight and doublecheck.

**Comment by krues8dr** [comment]
@waldoj can you confirm this one again? I think I've got it cleaned up.

**Comment by waldoj** [comment]
:+1: I fired up a clean install, with [statedecoded-vagrant](https://github.com/statedecoded/statedecoded-vagrant), replaced `/src/` with this branch, loaded `/admin/`, and did not see a SQL error on the initial load of the admin page.

**Comment by krues8dr** [comment]
:bomb:

**Comment by waldoj** [comment]
BTW, the Puppet install of Solr failed, because the mirror that Apache directed Puppet to didn't have v4.5 available. That seems like yet another reason to default to using MySQL instead of Solr.
