### ISSUE TITLE
Sidebars are too narrow at most breakpoints

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#567]
At most page widths, the sidebars are too narrow:

![columns](https://cloud.githubusercontent.com/assets/656758/5570370/3e31cc6e-8f4e-11e4-9168-96a91f809367.jpg)

Figure out why this is happening and fix it.

**Comment by waldoj** [comment]
This Masonry.js stuff makes my head spin. I _think_ it's `.grid-sizer` that needs to be modified, but it might be the `data-masonry-options` attribute of `div.js-masonry` in the sidebar. Whatever it is, I've gotta figure it out, because this standard layout looks _rough._

**Comment by krues8dr** [comment]
I'm tempted to rip Masonry out altogether – we only have but so many sidebars, and I don't see why we can't just stack 'em in the first place?  I only have at most 2-3 on any given page, and even some of the [uglier VA pages](https://vacode.org/4.1-200/) still look better with just a single sidebar instead of 3.

**Comment by boboroshi** [comment]
I agree with stacking them at this point. It was an experiment that didn’t work out as well as I’d hoped.

**Comment by krues8dr** [comment]
Hi @boboroshi ! 👋  Yeah, I think it was different back when screens were smaller and less retina'd a few years ago too.

**Comment by waldoj** [comment]
At just the right breakpoint, it works well, but most of the time, it's awkward. :-/

**Comment by boboroshi** [comment]
My only thought would be to not let them get too wide on their own. Line length is a concern in left side tho, so [insert shrug thingy here] :)

**Comment by krues8dr** [comment]
**CSS**

![blinds-dog](https://cloud.githubusercontent.com/assets/127904/21959996/d0a6bd52-daa6-11e6-8329-4697c2056aa8.gif)

**Comment by boboroshi** [comment]
And then we ran it through a new javascript preprocessor… YOU WON’T BELIEVE WHAT HAPPENS NEXT.
