### ISSUE TITLE
If no editions exist, the admin section doesn't work

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#569]
In the `edition-update` branch, the first load of `admin/index.php` yields this:

```
SQL: [48] SELECT * FROM editions ORDER BY order_by Params: 0
```

That's the only thing within the messages frame; no options are available.

The problem appears to be this line within `ParserController::show_admin_forms()`:

```php
$editions = $args['parser']->get_editions();
```

If I comment out that line, the page loads just fine.

My assumption is that `get_editions()` isn't prepared for the possibility that the `editions` table might not exist at all (as is the case on the first load of `/admin/`).

**Comment by krues8dr** [comment]
Ok, so instead of leaving the user to flounder - if this is a new installation, we prompt them to install the database.  I'm doing this not-automatically since it may be the result of a misconfiguration (and I'm providing links to the documentation then too).  I've also added to this to run any migrations if needed - also prompting the user (if they've updated their codebase but haven't updated their database yet).

**Comment by krues8dr** [comment]
Also, I didn't realize that `PDO's debugDumpParams()` actually prints out data instead of returning it ( :rage3: ) so I've fixed that up.

**Comment by waldoj** [comment]
> if this is a new installation, we prompt them to install the database. I'm doing this not-automatically since it may be the result of a misconfiguration (and I'm providing links to the documentation then too).

Wait, I'm confused. Why would we give up on automatically installing the database, which is how things work in master? Or when you say "prompt them," do you mean that it's automated, but the user has to click a button to make it happen?

**Comment by krues8dr** [comment]
The user has to click a button.
![screen shot 2015-01-05 at 9 15 09 pm](https://cloud.githubusercontent.com/assets/127904/5623317/f92199f6-951f-11e4-8030-beda64b32669.jpg)

**Comment by waldoj** [comment]
Oh, sweet. I'm totally down with button-clicking. :+1:

**Comment by krues8dr** [comment]
This is really just a "did I dun goofed?" button.

**Comment by krues8dr** [comment]
A very similar prompt appears if there are new migrations to run, for existing installations.

**Comment by waldoj** [comment]
I support minimization of goofing.

**Comment by krues8dr** [comment]
Can you give this a try and lmk if this is resolved?  #WorksForMe

**Comment by waldoj** [comment]
This is wholly resolved.
