### ISSUE TITLE
Add versioning to the API

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#571]
The API will inevitably change, and right now we have no intelligent way to handle that.  The sloppy approach is to add a query parameter, but the industry-strandard practice is to put the version up front in the URL (e.g. `/api/1.0/law/blah`).  [Here are some nice resources on the topic.](https://blog.apigee.com/taglist/versioning) 

* We should do this sooner rather than later, since we can still break things horribly for people now since we're a beta.  
* We'll probably want to harvest email addresses from the `api_keys1` table to notify our users.

**Comment by waldoj** [comment]
It _is_ versioned. Leaving out the version number is an alias to the current version. All API responses return the current API version, e.g.,:

`http://vacode.org/api/1.0dictionary/person?section=12.1-14&key=[api_key]` or 
`http://vacode.org/api/dictionary/person?section=12.1-14&key=[api_key]`:

```json
{
    "term": "person",
    "definition": "“Person” includes any individual, corporation, partnership, association, cooperative, limited liability company, trust, joint venture, government, political subdivision, or any other legal or commercial entity and any successor, representative, agent, agency, or instrumentality thereof.",
    "section_number": "1-230",
    "scope": "global",
    "url": "http://vacode.org/1-230/",
    "formatted": "“Person” includes any individual, corporation, partnership, association, cooperative, limited liability company, trust, joint venture, government, political subdivision, or any other legal or commercial entity and any successor, representative, agent, agency, or instrumentality thereof. (<a href=\"http://vacode.org/1-230/\">§&nbsp;1-230<\/a>)",
    "api_version": "1.0"
}
```

**Comment by krues8dr** [comment]
:+1: 

`Closed: rtfm.`
