### ISSUE TITLE
Importing fails on Solr 4.10.3

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#572]
A new minor version of Solr, a new Solr issue.  I've upgraded to 4.10.3 on a new server, but importing is no longer working.  Here's the error I'm getting on import: https://gist.github.com/krues8dr/855308c170eda9fc1c51   I've tried rebuilding the tokenizer but I'm still getting the same error.

I think this is still related to the custom tokenizer.  Considering the headaches that's caused us, I'd ideally like to migrate away from using that altogether if at all possible - it's broken on every upgrade we've done so far.

**Comment by waldoj** [comment]
Without a custom tokenizer, we can't index section numbers, though, right?

**Comment by krues8dr** [comment]
I'm not sure.  There's probably a different way to deal with this since we can control the format of the data we're importing.  [We're *only* using it on `index`, not on `query`](https://github.com/statedecoded/statedecoded/blob/master/solr_home/statedecoded/conf/schema.xml), so I suspect we could do the tokenization before it gets injested?

**Comment by krues8dr** [comment]
Here's what John Berryman has suggested:

```
If I was you I would completely remove RegexPathHierarchyTokenizer as a dependency and every time you use it in schema.xml replace it with 
       <charFilter class="solr.PatternReplaceCharFilterFactory" pattern="[\.-]" replacement="~"/>
       <!-- remove () or [] that somebody might use to identify a chapter -->
       <charFilter class="solr.PatternReplaceCharFilterFactory" pattern="\(.*?\)$" replacement=""/>
       <charFilter class="solr.PatternReplaceCharFilterFactory" pattern="\[.*?\]$" replacement=""/>
       <tokenizer class="solr.PathHierarchyTokenizerFactory" delimiter="~" />
       <filter class="solr.LowerCaseFilterFactory" />

The users should replace the green with any pattern that defines a delimiter and the blue with an single character that will not occur in a law/section/paragraph number. If I correctly recall, that will mostly replace the functionality of the RegexPathHierarchyTokenizer. The only concern though is that there was some other part of the functionality that needs something more complicated - and I can't remember what that was. I would experiment by creating different fieldTypes in the schema.xml to mimic what RegexPathHierarchyTokenizer does and then check out the Analysis screen for both of them (https://cwiki.apache.org/confluence/display/solr/Analysis+Screen) to see if you're making a close approximation. Just go to that page, select the experimental fieldTypes and pass sample text through (like 22.131--32:5) to see what tokens are produced. And remember, the query analyzer for a fieldType doesn't have to be the same thing as the tokens they produce do have it include some matches given the same input.
```

In green =  pattern="`[\.-]`" replacement="~"
In blue =  pattern="[\.-]" replacement="`~`"

**Comment by krues8dr** [comment]
@waldoj So, this tokenizes the section number - what are your expected search criteria and what should they match here?  Basically this is just splitting the groups of numbers into tokens, but I assume that if you search for "10.1" you only want "10.1" not "10-1" or "10" or "1" ?  That is, do we even need tokenization here?  The unit tests for the original shows "14-32.43-25"  yields tokens "14","14-32","14-32.43","14-32.43-25" - is that correct?

The other alternative is to do all the tokenization on the PHP side (as I'm having to do with a lot of the stuff in the editions work) and then just hand off those tokens to Solr - this seems like the easiest fix for us, at least.

**Comment by krues8dr** [comment]
Cleaned up a few more things on John's recommendation.
