### ISSUE TITLE
Support subsections that lack Identifiers

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#574]
I may have already opened this before, but I keep coming across it more and more often.  There are lots of legal codes that have a preamble, or other notes that are not purely attached to structures, just random pages glued in with everything else.  See [Miami-Dade Part II](https://library.municode.com/index.aspx?clientId=10620) or the [SF Charter](http://www.amlegal.com/library/ca/sfrancisco.shtml) for examples. 

In these cases, I'm inclined to:
- add a flag for the section_number to mark it as not-an-identifier in the database
- use this flag to determine if we should show the identifier as the heading of the row in the frontend display
- make this field much bigger to allow more content than just a number
- use that to generate the shortlink per the usual, after `slug`ification

**Comment by waldoj** [comment]
That's fascinating. I had no idea that was a thing. Do you have any sense as to how much content should be allowed? Is it elastic enough that we should go up to 255 characters, or perhaps even longer?

**Comment by krues8dr** [comment]
I honestly haven't done enough research to be sure.  I would be on board for 255, and if anyone has anything longer than that they'll just have to create a custom case in their parser to do anything smarter than just simple truncation.

**Comment by krues8dr** [comment]
(Updated the AMLegal link because it doesn't work to copy and paste their URLs.  Obvious comment redacted.)

**Comment by krues8dr** [comment]
Wordpress slugs are limited to 200 chars.

**Comment by waldoj** [comment]
Huh. That's a weird length. I'm surprised they didn't just go for 255. I'm sure there's some reason.

**Comment by krues8dr** [comment]
WP, have a reason?  `Legacy` most likely.

**Comment by krues8dr** [comment]
![screen shot 2017-03-19 at 1 17 16 pm](https://cloud.githubusercontent.com/assets/127904/24083057/6c658a6c-0ca6-11e7-823a-4f9c7bd69d3a.jpg)

**Comment by waldoj** [comment]
Makes sense to me!
