### ISSUE TITLE
Add Disqus tracking to Google Analytics

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#575]
There's a pretty simple way to record "Comment" events and pass them to Google Analytics, so I'm adding that right now.  Patch incoming.

**Comment by krues8dr** [comment]
Oh hey our GA code is waaaay out of date.  Gotta swap that out so this `undefined` error goes away.

**Comment by krues8dr** [comment]
Note that any derivative themes will need their theme's Page class updated to match.

**Comment by krues8dr** [comment]
![screen shot 2015-03-18 at 12 00 53 pm](https://cloud.githubusercontent.com/assets/127904/6715620/0b3d6316-cd76-11e4-85be-ea092ffa16c8.jpg)

Fantastic.

**Comment by waldoj** [comment]
Great!

**Comment by krues8dr** [comment]
One addendum to this - if you're doing any sort of subdomain routing like we do on [SanFrancisco Decoded](http://sanfranciscocode.org), you'll need this snippet, replacing your base domain name for `example.com`:

    _gaq.push(['_setDomainName', 'example.com']);
    _gaq.push(['_setAllowLinker', true]);
