### ISSUE TITLE
Permanent Identifier on Laws for Disqus

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#576]
While I'm working on Disqus, there's the issue with previous editions of laws not getting the old Disqus comments because the url has changed.  My gut here is to use the law identifier instead, since the identifier *almost* never changes.  And when it does, well, that's just weird law stuff, man.  

@waldoj thoughts?

**Comment by waldoj** [comment]
When I went with the default Disqus approach—using URLs as the unique identifier—it was with the understanding that previous editions would be displayed via URL fragments (per #362), since Disqus ignores URL fragments in identifying unique pages. Had we settled on a non-fragment-based approach?

**Comment by krues8dr** [comment]
I don't think we solved this officially.  I think fragments are a poor way to handle it because the server isn't doing the work, and swapping out the content with javascript seems hackish.  Also, less cacheable, prohibitive to linking to a previous editions' subparagraphs, and load-heavy (you're loading the content twice).

I'm using actual urls for these right now. I'm in favor of the way you're opposed to in that thread, with the edition identifier earlier in the url (`http://code.example.org/2011/1.23-45.6`) because it matches more semantically with the API versioning.  That works for most codes, because codes have a discreet edition for the whole code, not each individual law (as `http://code.example.org/1.23-45.6/2011/` would suggest).

**Comment by krues8dr** [comment]
That is in my brain, "I want the book (directory) labeled 2011 edition, and give me the laws in that book (directory)" makes the most sense.

**Comment by waldoj** [comment]
> prohibitive to linking to a previous editions' subparagraphs

This. D'oh!

OKOK, you're right. Structure in the URL. :(

**Comment by krues8dr** [comment]
And to the second half of that?

**Comment by waldoj** [comment]
I acquiesce to the whole thing. :)

**Comment by krues8dr** [comment]
#minor-victories :)
