### ISSUE TITLE
Put a CAPTCHA on the API registration form

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#580]
I'm getting a lot of spambots creating API accounts. Now that Google has a new iteration of CAPTCHA that isn't awful, that's probably the easiest way to stop that.

**Comment by krues8dr** [comment]
Can we make this optional? I'm ok with it defaulting to on, but I'd rather block by IPs than require a CAPTCHA if at all possible.

**Comment by waldoj** [comment]
It's all the same to me. :)

**Comment by waldoj** [comment]
[Using reCAPTCHA requires per-domain registration](https://www.google.com/recaptcha/admin), which in turn requires a Google account. This just seems like One More Damned Thing™ for people.

The good news, I guess, is that fake API accounts aren't really problematic. It's just one more entry in a database table, a table that only somebody mucking around in MySQL would ever see. Perhaps I just need to let this go.

**Comment by krues8dr** [comment]
:+1:
