### ISSUE TITLE
Check installation instructions

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#594]
These might be a bit out of date by now.

**Comment by waldoj** [comment]
As of the latest release, there's no need to install Solr, right?

**Comment by waldoj** [comment]
I'd check whether modern versions of Solr are available as RPM and DEB packages, but that's only going to end in heartbreak.

**Comment by krues8dr** [comment]
Right, Solr is now optional.  I'll check about packages.

**Comment by waldoj** [comment]
I should really format the installation instructions so that, instead of breaking it up by package and then by platform, instead just break it up by platform. Five `yum`s can be replaced with one, etc.

**Comment by krues8dr** [comment]
:+1:

**Comment by waldoj** [comment]
OK, done. That's a start.

**Comment by waldoj** [comment]
I just checked, and Solar 1.4.1 is still the version supported in packages. Solr 1.4.1 came out _6 years ago._ The current version is 6.0.1.

I'll never stop being surprised by the incompetence of the Solr community.

**Comment by krues8dr** [comment]
Just updated some info about Solr, otherwise this looks good.
