### ISSUE TITLE
Reconsider semantic markup of catch lines

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#599]
Right now, we put the section identifier in an H1, and the catch line in an H2, e.g.:

```
<h1>§ 18.2-250</h1>
<h2>Possession of controlled substances unlawful.</h2>
```

This is logical, but the effect of it is that Google thinks that the page title is `§ 18.2-250` (or, rather, `18.2-250`, for reasons that only Google knows), and that's a substantially less useful thing for somebody to see in search results than `Possession of controlled substances unlawful`. It seems to me that how we do it is "right," but that it's leading to a wrong outcome.

**Comment by krues8dr** [comment]
IMHO splitting that into a heading and sub-heading when it's technically *one piece* of semantic data seems crazy anyway.  Personally, I'd wrap the whole thing in an H1 and use spans/microformats inside to separate pieces.  Technically, headings should be the beginning of a new section, and this markup indicates that there will be other `<h2>` titled content pieces to follow the Possession section.

**Comment by boboroshi** [comment]
Id probably go with the whole things as an h1 and wrap the current h1 in a span for styling purposes (eg display: block to break the line and other current h1 styles).

**Comment by waldoj** [comment]
I think this is in the category of It Seemed Like a Good Idea at the Time.

**Comment by boboroshi** [comment]
That and semantic markup has numerous camps and shifts faster than the sands of the Sahara.
