### ISSUE TITLE
Don't break when google ad links come in.

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#602]
Google likes to append things like `?gclid=CjwKEAiAw4e1BRDfi7vghaWU9jESJACzo9juyqmPwqpRWWS9G9NdCWgaYXaVDo1JeCr78JNjgiSi_xoCqhLw_wcB%201%20Comment` to urls, which unfortunately causes SD to die horribly.  I guess we need a way to ignore query strings like that?

**Comment by waldoj** [comment]
Huh. That's an interesting problem. It seems we could either a) whitelist acceptable query strings or b) blacklist unacceptable ones. Given that the range of B is enormous, but the range of A is quite narrow, I think A is our only option.

Offhand, the only places on the site that I can think of where we're using query strings are a) search and b) API key activation. If that really is it, then whitelisting should be quite straightforward.

**Comment by krues8dr** [comment]
I'm more confused that PHP is balking at query strings in the first place - usually you can do whatever you want on that front without it caring.

**Comment by waldoj** [comment]
I actually can't replicate the problem. On Virginia Decoded, [the query string you suggested](https://vacode.org/57-2/?gclid=CjwKEAiAw4e1BRDfi7vghaWU9jESJACzo9juyqmPwqpRWWS9G9NdCWgaYXaVDo1JeCr78JNjgiSi_xoCqhLw_wcB%201%20Comment) works just fine.

**Comment by krues8dr** [comment]
Au contraire [on the root it 404s](https://vacode.org/?gclid=CjwKEAiAw4e1BRDfi7vghaWU9jESJACzo9juyqmPwqpRWWS9G9NdCWgaYXaVDo1JeCr78JNjgiSi_xoCqhLw_wcB%201%20Comment)

**Comment by waldoj** [comment]
Oh, that's interesting. So that would seem to point to a routing problem.

**Comment by krues8dr** [comment]
Routing _feature_.

**Comment by waldoj** [comment]
Two sides of the same coin. ;)

**Comment by krues8dr** [comment]
That should do it.

**Comment by waldoj** [comment]
:+1:
