### ISSUE TITLE
/api-key/ returns a 500 error (and user presented with a blank page)

### ISSUE THREAD

**Issue by dstricks** [statedecoded/statedecoded#603]
Examples:
`http://chicagocode.org/api-key/`
`https://vacode.org/api-key/`

I stumbled upon this because [The State Decoded API documentation](http://statedecoded.github.io/documentation/api.html) has: 

> Register for a key on the site in question (e.g., Virginia)

... with `https://vacode.org/api-key/` being the href. 

It appears that this `../api-key/ ` page *should* be a valid location because visiting `https://vacode.org/blah/ `properly presents a 404.

**Comment by waldoj** [comment]
Ack! I don't know how in the world that got through to deployed software! I'll pore over the error logs and figure out what's up. Thanks so much, @dstricks.

**Comment by waldoj** [comment]
```
PHP Fatal error:  Class 'ApiKeyController' not found in /vol/vacode.org/includes/class.MasterController.inc.php on line 38
```

Well, yeah, that'll do it.

**Comment by krues8dr** [comment]
This looks like my doing, I'll take a look this morning.  Should be easy.

**Comment by krues8dr** [comment]
Oh wait, that's just to register for an API key, so this is all on the Downloads page now since the redesign.  So it's just a documentation issue?  @waldoj am I crazy or is that right?

**Comment by waldoj** [comment]
Huh. I'm pretty sure you're right. So this requires a) fixing the docs and b) figuring out why in the world a 500 results, instead of a 404.

**Comment by krues8dr** [comment]
I'm looking at the 500 right this minute for #602

**Comment by waldoj** [comment]
Ahh, right, I thought I remembered that. Great. I'll fix the docs then.

**Comment by krues8dr** [comment]
Ok, there's the 500 fix.  :+1:
