### ISSUE TITLE
CourtListener API version is being deprecated

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#604]
[The version of CourtListener's API that we're using is being deprecated](https://free.law/2016/01/31/releasing-v3-of-the-api-deprecating-v1-and-v2/), and pretty rapidly. By March 31, it will return blank JSON files. The good news is that it looks like it's going to be a really easy upgrade—possibly as simple as just changing `1` to `3` in the URL. Existing sites can be upgraded just by making that change.

**Comment by waldoj** [comment]
Er, after reviewing things more closely—that is not true. A bunch of variables changed. Nothing serious, nothing a simple patch can't address.

**Comment by waldoj** [comment]
@krues8dr, do y'all use this method on any of your sites?

**Comment by krues8dr** [comment]
Not currently, shouldn't affect us right now.

**Comment by waldoj** [comment]
:+1: Thanks!

**Comment by waldoj** [comment]
Tested, corrected, works great. Merging branch.
