### ISSUE TITLE
Setup fails without errors

### ISSUE THREAD

**Issue by cmbirk** [statedecoded/statedecoded#607]
I'm getting this page on a new installation, but no errors are being shown.
<img width="1407" alt="screen shot 2016-06-01 at 12 52 16 pm" src="https://cloud.githubusercontent.com/assets/764851/15719909/b1a77f16-27f7-11e6-899b-eba1d9c965b7.png">

I'm getting the following in the error logs:

```

[Wed Jun 01 12:51:12.048335 2016] [:error] [pid 98208] [client 127.0.0.1:58587] PHP Fatal error:  Uncaught exception 'Exception' with message 'Array\n(\n    [Query] => SELECT *\n\t\t\t\tFROM permalinks\n\t\t\t\tWHERE url = :url\n\t\t\t\tLIMIT 1\n    [Statement Code] => 42S02\n    [Statement Info] => Array\n        (\n            [0] => 42S02\n            [1] => 1146\n            [2] => Table 'nyccode.permalinks' doesn't exist\n        )\n\n    [Database Code] => 00000\n    [Database Info] => Array\n        (\n            [0] => 00000\n            [1] => \n            [2] => \n        )\n\n    [Input Parameters] => Array\n        (\n            [:url] => /favicon.ico/\n        )\n\n    [Statement Parameters] => SQL: [61] SELECT *\n\t\t\t\tFROM permalinks\n\t\t\t\tWHERE url = :url\n\t\t\t\tLIMIT 1\nParams:  1\nKey: Name: [4] :url\nparamno=-1\nname=[4] ":url"\nis_param=1\nparam_type=2\n\n)\n' in /Users/cmbirk/Sites/AMLegal/new-york/includes/class.DatabaseStatement.inc.php:103\nStack trace:\n#0 /Users/cmbirk/Sites/AMLegal/new-york/includes/class.PermalinkController.inc.php(69): DatabaseStatement->execute(Array)\n#1 /Users/cmbirk/Sites/AMLegal/new-york/includes/class.Permali in /Users/cmbirk/Sites/AMLegal/new-york/includes/class.DatabaseStatement.inc.php on line 103, referer: http://local.nyccode.com/admin/

```

It's looking for the database to be already set up, but the installation instructions say to modify the parser and navigate to `/admin`, which I assumed would have steps for setting up the database ( going with the modify class method ).

**Comment by krues8dr** [comment]
The admin page is supposed to automatically setup the database, so something funny is happening here.  First guess is improperly configured database settings.

**Comment by cmbirk** [comment]
I changed the log level from 5 to 1 and got the errors that the `sitemap.xml` and `.htaccess` files needed write access from the server.  Should we just default the log level to 1 in the config for new setups?

**Comment by krues8dr** [comment]
No, we should definitely just improve the error-checking. ;)  Level 1 is *super-verbose*.

**Comment by cmbirk** [comment]
Yep, finding that out now on the import.  _Everything_ is logged to the admin page

**Comment by waldoj** [comment]
So I think the solution here is to ensure that the default verbosity level permits any show-stopping errors to be displayed, right? Presumably that means either just changing the default verbosity level or auditing all of the error messages to ensure that they're consistent in their log level. Does that make sense to you, @krues8dr?

**Comment by krues8dr** [comment]
I updated the levels a while back, and this appears to be reporting the env test errors correctly now.  The test environment command reports all errors at a verbosity of 10, so even if someone has changed that from the default (5) they'll still show up.
