### ISSUE TITLE
American Legal parser errors

### ISSUE THREAD

**Issue by cmbirk** [statedecoded/statedecoded#608]
I'm getting these errors when trying to import the administrative code

```

Notice: Trying to get property of non-object in /Users/cmbirk/Sites/AMLegal/new-york/includes/class.Search.inc.php on line 110
Beginning import
Environment test succeeded

Notice: Trying to get property of non-object in /Users/cmbirk/Sites/AMLegal/new-york/includes/class.ParserController.inc.php on line 316
Wrote edition ID to .htaccess

Notice: Undefined index: edition in /Users/cmbirk/Sites/AMLegal/new-york/htdocs/admin/index.php on line 273
Deleted dictionary
Deleted laws
Deleted laws_references
Deleted text
Deleted text_sections
Deleted tags
Deleted structure
Deleted permalinks
Deleted laws_meta
Beginning the import process
Import error: Array ( [Query] => SELECT label FROM structure GROUP BY label ORDER BY depth ASC [Statement Code] => 42000 [Statement Info] => Array ( [0] => 42000 [1] => 1055 [2] => Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'nyccode.structure.depth' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by ) [Database Code] => 00000 [Database Info] => Array ( [0] => 00000 [1] => [2] => ) [Input Parameters] => [Statement Parameters] => SQL: [61] SELECT label FROM structure GROUP BY label ORDER BY depth ASC Params: 0 ) 
Done

Back
Notice: Undefined variable: body in /Users/cmbirk/Sites/AMLegal/new-york/htdocs/admin/index.php on line 381

```

Still looking into the cause

**Comment by krues8dr** [comment]
Looks like an incompatible MySQL version to me.  If you're in the 5.5-5.6 range you should be safe.

**Comment by cmbirk** [comment]
Yep, I'm using 5.7.11.  I'll give a lower version a try

**Comment by djeraseit** [comment]
That error is caused by using the newer version of MySQL, the query needs to be rewritten.

**Comment by djeraseit** [comment]
try adding id field: GROUP BY id, label

**Comment by waldoj** [comment]
There is valid SQL that worked in v5.6 and now _don't_ work in v5.7?

**Comment by krues8dr** [comment]
Yeah they changed the requirements on GROUP clauses.  Ugh.

**Comment by djeraseit** [comment]
It was never proper to use Group By in that manner. The newer versions of MySQL are strict by default.

**Comment by waldoj** [comment]
Aw, man, that's a lousy thing to do. Is it possible to write a v5.7-compatible GROUP clause that will also work in older versions? (If not, I'm going to have a hard time selecting exactly which anigif expresses my feelings out the matter.)

**Comment by djeraseit** [comment]
yes, adding the id field should do the trick

**Comment by krues8dr** [comment]
Yeah, it is possible.  I think we've still got some queries we wrote which will stand up in MySQL 3.23 frankly. ;)

**Comment by cmbirk** [comment]
@djeraseit can you point me to where that query gets built?

**Comment by krues8dr** [comment]
@cmbirk That query is, I'm pretty sure, from `get_structure_labels()` in the Parser class (and/or AmericanLegal parser class).

**Comment by cmbirk** [comment]
@krues8dr yep, found it.  Thank you sir.

**Comment by krues8dr** [comment]
I think in this case adding `SELECT DISTINCT` and removing the `GROUP` clause might also solve this.

**Comment by djeraseit** [comment]
root@lewis:/var/www/html/decoded.civilsoot.com/public_html/statedecoded-0.9# grep -r "GROUP BY"
includes/class.Texas.inc.php:           $sql = 'SELECT label FROM structure GROUP BY label ' .
includes/class.State-sample.inc.php:            $sql = 'SELECT label FROM structure GROUP BY label ' .
includes/class.AmericanLegal.inc.php:           $sql = 'SELECT label FROM structure GROUP BY label ' .
includes/class.Law.inc.php:                                             GROUP BY text_id) AS prefixes
includes/class.Municode.inc.php:                $sql = 'SELECT label FROM structure GROUP BY label ' .
includes/class.Structure.inc.php:                * If we're sorting children by views, we need to insert a GROUP BY and ORDER BY statement
includes/class.Structure.inc.php:                       $sql .= '       GROUP BY structure.id

**Comment by cmbirk** [comment]
Adding `id` here worked.  I will open a PR with that fix

**Comment by cmbirk** [comment]
I take that back.  We'll have to use the `distinct label` query as mentioned above.

**Comment by cmbirk** [comment]
`SELECT distinct label, depth FROM structure ORDER BY depth ASC`
