### ISSUE TITLE
Indicate progress of import process

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#618]
When running an import, status messages get as far as `Beginning the import process`, and then there's a delay of minutes or hours while the XML files are imported. We should indicate in some way that this is proceeding, even if it's just to say "importing 12,345 files—this may take a while" or something like that. Maybe display a spinner.

**Comment by waldoj** [comment]
Progress is hard, because of the hacky method that we use to show output a frame. Even a spinner is hard. But showing the number of files shouldn't be too hard. I think the place for it is the ParserController constructor method. I'm tempted to do this non-recursively, since [our included parser doesn't recurse](https://github.com/statedecoded/statedecoded/blob/b47fb0a96d578925edcbd76507a36b2242a0bf1b/includes/class.State-sample.inc.php#L332), but the decoupled nature of the two makes that a bad idea. PHP appears to have no decent method of recursively listing directory contents. Maybe dropping to the shell to use `find` is the way to accomplish this?

**Comment by krues8dr** [comment]
I would really, really strongly suggest punting on this (as we talked about two years ago when it was brought up).  The synchronous way that we're handling this currently is really not ideal, and imho it'd be better to rewrite the bulk of it to not be entirely web-based than keep hacking stuff onto a process that should be mainly server-side anyway. That's the direction I've been heading with the command line importer at least.

**Comment by krues8dr** [comment]
#125 is the relevant discussion on this.

**Comment by krues8dr** [comment]
I added progress bars for the two longest processes: the import parsing and export.

![screen shot 2017-01-14 at 5 40 57 pm](https://cloud.githubusercontent.com/assets/127904/21958637/be03369c-da80-11e6-9482-b34604199b2f.jpg)

**Comment by waldoj** [comment]
Yay! Great UI improvement. :)
