### ISSUE TITLE
Don't check for canonical URL at the top structural level

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#619]
Doing so just yields a PHP notice, because we're calling `Permalink::get_permalink()` with a blank structure ID.

**Comment by krues8dr** [comment]
Is this true even if you have multiple editions?  I seem to remember this being critical to allow users to browse not-current editions... but it's been a while since I looked at this.

**Comment by waldoj** [comment]
This shouldn't be critical for _anything,_ since this is only about injecting a `<link rel="canonical">` tag if the request is for a URL that doesn't match the canonical URL. But I only tested this in an environment with a single

**Comment by krues8dr** [comment]
Looks ok.
