### ISSUE TITLE
Sanity test for bulk download generation is flawed

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#621]
While performing a bulk import, I got this error:

```
Error: /vol/beta.vacode.org/htdocs//downloads/2016/ could not be written to, so bulk download files could not be exported
```

But the files were written successfully to `downloads/2016/`, so that's incorrect. Do two things:
- [ ] fix the test so that it reflects reality
- [ ] if the test fails, don't try to write the files

**Comment by waldoj** [comment]
Huh. I don't get it. [This looks pretty straightforward](https://github.com/statedecoded/statedecoded/blob/3cf6ca1224ab3d3c0d2ce32aeeec012c42ddd577/includes/class.ParserController.inc.php#L1722):
```
if (is_writable($this->downloads_dir) === FALSE) {...}
```

**Comment by waldoj** [comment]
I wonder if the double slash (`htdocs//downloads`) is the problem? It certainly shouldn't be. But that ought to be eliminated anyway, so I'll try that.

**Comment by krues8dr** [comment]
You'd probably be best off using [Xdebug](https://xdebug.org/docs/profiler) to profile this.

**Comment by krues8dr** [comment]
Wrong issue for my comment.  Moving. :/

**Comment by krues8dr** [comment]
Slashes _shouldn't_ have anything to do with it.  The first thing that comes to mind is permissions - by default PHP in safe mode doesn't check group permissions, only user permissions, which will lead to a false negative on some systems.

**Comment by krues8dr** [comment]
`safe_mode_gid` is the flag to disable that.

**Comment by waldoj** [comment]
Ah-ha, that does seem like a likely culprit. I'll check that.

**Comment by loandy** [comment]
Looking into this issue, it kind of looks like this is one of the many bad corners of PHP.  Should this be a case where we should ask forgiveness instead of permission and handle exceptions instead of the upfront sanity check?

**Comment by waldoj** [comment]
That'd be a tough exception to handle. The setup process is non-interactive, so handling an exception would mean overhauling that, so that the user could intervene. :-/

Huh, `safe_mode_gid` was disabled in PHP v5.4. OK, that's a rabbit hole to dive into.

I'm going to play with this test to identify what the problem is that I'm having with it, and figure out how to modify the test to accommodate that. It could be permissions, maybe it's something else, but I'll look into it.
