### ISSUE TITLE
Many XML exports are failing

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#624]
When exporting producing bulk downloads and static files, many (every?) attempt to export XML results in an error being thrown:

```
PHP Warning:  SimpleXMLElement::asXML(): xmlEscapeEntities : char out of range in /vol/beta.vacode.org/includes/class.ParserController.inc.php on line 1491
```

There's no way that so many laws contain characters that are problematic. Figure out what's triggering this and fix it.

**Comment by krues8dr** [comment]
I'm 99% sure this is an issue I brought up previously, but can't find it immediately - there are hidden/whitespace characters in most of the XML documents I encountered as well.  I *think* I recall this being resolved by upgrading some underlying XML library, fwiw.

**Comment by waldoj** [comment]
Man, I hope so. It's goofy that PHP's XML library can't deal with this natively. If there's an invalid character, there should be an option to strip it out.

**Comment by krues8dr** [comment]
https://github.com/statedecoded/statedecoded/issues/433 seems relevant

**Comment by krues8dr** [comment]
E.g. https://github.com/statedecoded/statedecoded/commit/cfa2c4c6805d946468917d7a046725fcf39de93a

**Comment by waldoj** [comment]
Sometimes, [Past Waldo is an OK guy](https://github.com/statedecoded/statedecoded/issues/433#issuecomment-67798081).
