### ISSUE TITLE
Environment-testing log messages should all be level 10

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#625]
If somebody has their error verbosity at the default level (level 5), and they run the environment test, they will not see those tests with a verbosity level below 5. This means that an attempt to run the parser could fail without any displayed error message.

Either raise the verbosity level of every test to 10 or temporarily suspend the verbosity threshold for the duration of the environment test.

**Comment by krues8dr** [comment]
You want to do the former here.  Please don't mess with the default verbosity settings, it would be crossing the streams.
