### ISSUE TITLE
Download path generation/handling for current editions is running into problems

### ISSUE THREAD

**Issue by loandy** [statedecoded/statedecoded#628]
Whenever I make an edition current when importing, whether creating or updating an edition, the download directory path being generated seems to be lacking an intermediate slash between the download directory/url and the edition slug (e.g. If I were to create an edition called new, it creates a directory under `htdocs` called `downloadsnew` instead of a subdirectory like `downloads/new`).

Lines 440-441 of `includes/class.ParserController.inc.php` seem to bear this out, but I wanted to check if something wasn't somehow wrong in my environment.

**Comment by krues8dr** [comment]
Assuming you've got a current build from `master`, I'm guessing this is from @waldoj 's change in 1eab388c80ea3f1fa52f7c0ac06977a51ab59bc7

**Comment by krues8dr** [comment]
Hmm.  Maybe not.  We hardcode the extra slash in a lot of places, I'm not sure what would remove it.

**Comment by loandy** [comment]
It looks like trailing delimiters are removed by realpath(): http://php.net/manual/en/function.realpath.php

**Comment by krues8dr** [comment]
Well, have you pulled since he fixed that then?  :)

**Comment by loandy** [comment]
Commit b47fb0a is the latest change that we're running on right now, which should be one short of the latest on the `statedecoded` master.

**Comment by waldoj** [comment]
Ah, interesting—further evidence of the unreliability of relying on the presence (or non-presence) of slashes within directory paths, between distributions. It seems to me that we need to `ParserController::set_edition` to add a potentially duplicate slash, and then eliminate duplicate slashes. It's not glamorous, but I think it's the best solution. (We wouldn't use `realpath()` because that's for absolute filesystem paths, not URLs.)

Sot the function looks like this right now:
```php
$this->edition = $edition;
$this->downloads_dir .= $edition->slug . '/';
$this->downloads_url .= $edition->slug . '/';
```
And we'd make it this:
```php
$this->edition = $edition;
$this->downloads_dir .= str_replace('//', '/', '/' . $edition->slug . '/');
$this->downloads_url .= str_replace('//', '/', '/' . $edition->slug . '/');
```
That said, `realpath()` is for filesystem paths, not URLs. So it might make more sense to do a `str_replace` of `//` with `/`?

**Comment by loandy** [comment]
It's not pretty, but it looks like it should work while being pretty straightforward.

**Comment by loandy** [comment]
It doesn't look like the `downloads_dir` attribute should be modified between the call to realpath() and its modification under the set_edition() method, so duplicate trailing slashes *shouldn't* be a worry.  If we're so inclined though, we might as well squash all duplicated slashes.

**Comment by krues8dr** [comment]
Assuming we don't want to use one of the modern Composer packages for this, moving forward I'd recommend:

1) not ever using slashes in our code (for cross-platform-ability) and
2) replacing all the string mangling with [a function like this](http://www.bin-co.com/php/scripts/filesystem/join_path/) to do the work for us

**Comment by waldoj** [comment]
Presumably we'd use the `DIRECTORY_SEPARATOR` constant instead of slashes?

**Comment by krues8dr** [comment]
Yup, that's the idea.  Also, I just ran aground on this issue myself since updating.  And also the group permission problem.  Sending up a patch for this real quick.
