### ISSUE TITLE
Default utf8_bin collation causing issues with fulltext search

### ISSUE THREAD

**Issue by loandy** [statedecoded/statedecoded#629]
I believe the utf8_bin collation on many of the table definitions in `htdocs/admin/statedecoded.sql` is causing issues when using MySQL's search instead of Solr.  Search effectively becomes case-sensitive (or exact).

Changing the collation to utf8_general_ci and regenerating the tables seemed to fix this issue for me on both my local development environment and our staging environment.  Is there a reason the collation for everything remains in utf8_bin?  Let me know if I'm doing something wrong.

**Comment by krues8dr** [comment]
I'm not aware of any reason we're using utf8_bin - we can probably change those out.  We'll need to [write a migration](https://github.com/statedecoded/statedecoded/tree/master/includes/migrations) to do this.

**Comment by waldoj** [comment]
I started using utf8_bin out of habit in maybe 2004, occasionally reinforced by various best-practices guides that recommended the same. (MySQL's defaults for this have changed over the years, complicating things.) After just a few minutes of research, it sure seems like a sensible change to make, to ensure that MySQL-based search works optimally on every setup.

**Comment by waldoj** [comment]
Thanks for this proposed change, @loandy!
