### ISSUE TITLE
Definitions are wrongly being scoped as global

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#634]
The stock definition parser in `class.State-sample.inc.php` (as shipped with v0.9, but apparently unchanged since then) has something awry—it's scoping hundreds of definitions as global, when they are certainly not. 

Having only read through the code—I haven't tested anything—I speculate that the problem might stem from a mismatched pair of assumptions. [We start `extract_definitions()`](https://github.com/statedecoded/statedecoded/blob/master/includes/class.State-sample.inc.php#L1792) with
```php
$scope = 'global';
```
which is to say that we _begin_ with the assumption that the scope is global.

Then we try to match the scope with a known structural label, and if that fails, then we assume that the scope is limited to that law:
```
$scope = end($structure_labels);
```
What's with this mismatch? It _may_ be a result of how we walk the array, starting with the first element. But it may also be a bad opening assumption that's in need of correcting. In theory, if we can't calculate scope, we should be defaulting to law (per the prior code snippet), but if something is going wrong here, we might be defaulting to global instead of the law.

**Comment by krues8dr** [comment]
I had some scope issues with the American Legal parser a while back that sound similar to this, and I resolved those here: https://github.com/statedecoded/statedecoded/commit/4ec3bdcc9034f751d0991667266ee23f77f887b0#diff-546afb6a3141aa941d85b6ab5560fa52R1590

**Comment by waldoj** [comment]
It looks like that made it into v0.9, so I'm already working off of that code.

**Comment by waldoj** [comment]
Yup, the default of `global` was the problem.
