### ISSUE TITLE
Fix typo in search.php result iteration loop

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#644]
In the `foreach ($results) {}` loop in `search.php`, a mistyped variable name results in trying to use `strpos()` on an object, instead of on a string. Fix that.

**Comment by krues8dr** [comment]
Relatedly: I really, really need to start using a better IDE.

**Comment by waldoj** [comment]
I should start using an IDE at _all._ Every couple of years, I try something and just _hate_ it. I want, like, 10% of the features of an IDE.

**Comment by krues8dr** [comment]
People like PHPStorm a lot - I used IntelliJ (actually the same thing under the hood) with the PHP plugin for a bit but it just felt clunky.  Probably should switch back.

**Comment by waldoj** [comment]
@krues8dr, I need another set of eyes on [this](https://github.com/statedecoded/statedecoded/blob/master/htdocs/search.php#L178):

```
foreach ($results->get_results() as $result)
{
	$law->law_id = $result->law_id;
	$law->get_law();

	$url = $law->get_url( $result->law_id );
	$url_string = $url->url;

	if (strpos($url, '?') !== FALSE)
	{
		$url_string .= '?';
	}
	else
	{
		$url_string .= '*';
	}
	$url_string .= 'q='.urlencode($q);
}
```
This bit—`if (strpos($url, '?') !== FALSE)`—is clearly wrong. The obvious fix is to change `$url` to `$url_string`, but why in the world would we want to append `?` to a URL that already contains one?

**Comment by krues8dr** [comment]
I'm not sure why any of that is what it is - why the heck would I append `*` instead of `&` ?  It's possible I typo'd the whole thing poorly.

**Comment by krues8dr** [comment]
If so, this is terribly sloppy work on my part.

**Comment by waldoj** [comment]
Oh, I dunno, this has all of the hallmarks of a Waldo Special®.

**Comment by waldoj** [comment]
Hey, [it _was_ you](https://github.com/statedecoded/statedecoded/blame/master/htdocs/search.php#L178)! Phew. ;)

**Comment by krues8dr** [comment]
Yup.  I'm digging through my inbox and can't even find any documentation on why I was working on that that day.  :/  Definitely made a mess of things. 🚫 :shipit:

**Comment by waldoj** [comment]
> The obvious fix is to change `$url` to `$url_string`

Obvious...and wrong. This just yielded URLs with `*` in place of `?`. On Virginia Decoded, I just collapsed all of this into appending `'?q='.urlencode($q)` to the URL until I figure this out.
