### ISSUE TITLE
structure table is capped at 65,535 entries

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#645]
That might seem like a reasonably large number, but performing repeated updates of a legal code that's subdivided into a cumulative thousands of structural units is enough to hit that cap. Change that from `smallint` to `mediumint`, and write a migration for that. (Thanks to a foreign key relationship on `structure.id`, this isn't just a one-liner.)

**Comment by krues8dr** [comment]
If you're gonna do this, please go ahead and make this an `int unsigned` - with my editions work and the size of some of these city codes I've got, I'm probably gonna max out mediumint eventually.  And space is cheap.

**Comment by waldoj** [comment]
Oh, man, did I get lost here. (I switched computers midway through this, and everything went sideways.) I _think_ this is how I did it?

```sql
ALTER TABLE structure DROP FOREIGN KEY structure_editions;
ALTER TABLE laws DROP FOREIGN KEY `laws_structure`;
ALTER TABLE structure MODIFY id INT UNSIGNED;
ALTER TABLE laws CONSTRAINT `laws_structure` FOREIGN KEY (`structure_id`) REFERENCES `structure` (`id`) ON DELETE CASCADE;
ALTER TABLE `structure` ADD CONSTRAINT `structure_editions` FOREIGN KEY `edition_id` (`edition_id`) REFERENCES `editions` (`id`) ON DELETE CASCADE;
```
It'll be necessary to test this out on a clean v0.9 installation before I can put together a migration.

**Comment by krues8dr** [comment]
Is structure_id on laws already an int? The types have to match.

**Comment by krues8dr** [comment]
Also I'm not sure what structure_editions has to do with anything here.

**Comment by waldoj** [comment]
I got lost in dependencies. :-/

**Comment by krues8dr** [comment]
You want me to have a go at it?

**Comment by waldoj** [comment]
I think so. I'm not sure how such a simple thing manages to get me so turned around. :)
