### ISSUE TITLE
Pages not found yield a 500 instead of a 404

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#655]
I'm assuming this is a problem with the router, but I'm not sure.

**Comment by krues8dr** [comment]
Yes, I think I know exactly what this is actually.

**Comment by krues8dr** [comment]
Wait, maybe not.  Did I fix this at some point?

![screen shot 2016-08-31 at 9 22 35 pm](https://cloud.githubusercontent.com/assets/127904/18152051/23d63f94-6fc1-11e6-9dd5-7e6f36fcdb8a.jpg)

**Comment by waldoj** [comment]
Huh. Maybe after v0.9? (That's what Virginia Decoded is running.) I'll check on that.

**Comment by krues8dr** [comment]
Can you give a url where this is happening?  My initial guess is the checks in the `PermalinkController` are somehow causing a class to be attempted to be instantiated when it doesn't exist, but I thought I added a try/catch since then.

**Comment by krues8dr** [comment]
Your error log would say something about "no such class" or whatever PHP says in that case.

**Comment by waldoj** [comment]
Sure, any non-existent URL, e.g. https://vacode.org/404/.

**Comment by krues8dr** [comment]
Yeah, so I think I fixed this at some point?  Chicago works (newest version): https://chicagocode.org/fdjsaklfjdsalk/  but SF fails (older version): http://administrative.sanfranciscocode.org/sdfafdsa/

**Comment by waldoj** [comment]
Ah, right—logs. :-/

>[Wed Aug 31 21:30:10.674365 2016] [:error] [pid 18762] [client 70.199.194.71:10119] PHP Fatal error:  Class 'Controller' not found in /vol/vacode.org/includes/class.PermalinkController.inc.php on line 35

**Comment by krues8dr** [comment]
https://github.com/statedecoded/statedecoded/commit/f89d199c19047a0f88451ac167226569f817c867

**Comment by waldoj** [comment]
Ahhhh, that's much better. :) Thank you!

**Comment by krues8dr** [comment]
![](http://i.imgur.com/ZQbql0J.gif)
