### ISSUE TITLE
Structural context prose handles nesting poorly

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#656]
[For example](https://vacode.org/2.2/II/B/38/):

> This is Chapter 38 of the Code of Virginia, titled “Government Data Collection And Dissemination Practices Act.” It is part of Title 2.2, titled “Administration Of Government.” It is part of Subtitle II, titled “Administration Of State Government.” It is part of Part B, titled “Transaction Of Public Business.” It’s comprised of the following 12 sections.

I wrote this without thinking about how deeply nested some legal codes are. The text, as written, isn't _wrong,_ but it's confusing, because it fails to indicate that these are nested (as opposed to adjacent).

**Comment by krues8dr** [comment]
> This is Part C of the Code of State, titled “State Agencies Related To The General Operation Of Government.”, which is part of Subtitle I, titled “Organization Of State Government, which is part of Title 2.2, titled “Administration Of Government. It contains 1 laws divided across 2 structures.

Is this better? Or should we only show the current parent instead of the whole ancestry?

**Comment by waldoj** [comment]
I think this is much better. I think it's better to show the whole ancestry, because I've seen how confusing people find it when trying to understand what e.g. subtitle that a law is part of. Providing that as prose is a pretty helpful thing.
