### ISSUE TITLE
Deploying php project on linux server 

### ISSUE THREAD

**Issue by sayjavajava** [statedecoded/statedecoded#657]
My project that is working properly in windows . now i am deploying on Linux server . 

i have defined INCLUDES_PATH  in windows

  `  C:/xampp/htdocs/cms-includes`

that was giving me error like failed to open file because there is no C:\ or D: in linux . so i have to changed that in LINUX .

 

    `define('INCLUDES_PATH','C:/xampp/htdocs/cms-includes/');`

but i am getting these errors . 

```
       ```
 Fatal error in line 17 of file/var/www/web_loan/xampp/htdocs/cms-includes/init.i                                                                                        nc.php
    - Use of undefined constant INCLUDES_PATH - assumed &#039;INCLUDES_PATH&#039;
    
    Wed, 28 Sep 2016 01:53:37 -0500
    Fatal error in line 20 of file/var/www/web_loan/xampp/htdocs/cms-includes/init.i                                                                                        nc.php
    - Use of undefined constant INCLUDES_PATH - assumed &#039;INCLUDES_PATH&#039;
    
    Wed, 28 Sep 2016 01:53:37 -0500
    Fatal error in line 20 of file/var/www/web_loan/xampp/htdocs/cms-includes/init.i                                                                                        nc.php
    - require_once(INCLUDES_PATHclass.phpmailer.php): failed to open stream: No such                                                                                         file or directory
    
    PHP Fatal error:  require_once(): Failed opening required 'INCLUDES_PATHclass.ph                                                                                        pmailer.php' (include_path='/var/www/web_loan/xampp/htdocs/cms-includes:/var/www                                                                                        /web_loan/xampp/htdocs/cms-includes/pear:.:/usr/share/pear:/usr/share/php') in /                                                                                        var/www/web_loan/xampp/htdocs/cms-includes/init.inc.php on line 20
```
```

**Comment by krues8dr** [comment]
I'm afraid that this doesn't appear to be an error from State Decoded, we don't have a class called `phpmailer`.  Perhaps this is coming from somewhere else?

**Comment by sayjavajava** [comment]
i set path in index.php file and solved that .
