### ISSUE TITLE
XML output is incorrect

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#690]
It looks like sections are being garbled pretty bad.  This is since the export refactor and replacing SimpleXML, so there's lots here to look at.  I think the old method of just assuming that the law will nicely structure itself into well-formatted XML is no longer ideal, I think a more manual approach would be useful here to account for all the changes recently.

**Comment by krues8dr** [comment]
E.g. https://gist.github.com/krues8dr/a67563d9c4fcf39f13cb5e9e8ad581c6

**Comment by waldoj** [comment]
Ruh-roh.

**Comment by krues8dr** [comment]
Ok, I created yet another DOMDocument wrapper class, this time for _writing_ XML.  This makes creating XML documents way easier, and hopefully much more intuitive (and similar to other languages).
