### ISSUE TITLE
Handle ridiculously long dictionary terms.

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#699]
VA 38.2-2232 brings us this gem:

> For purposes of this section, a "new or renewal policy or contract covering liability arising from the ownership, maintenance or use of a private pleasure watercraft" shall mean and include only a policy or contract of marine protection and indemnity insurance, as defined in subsection B of § 38.2-126, written as a separate policy, which is not in combination with any other class of insurance defined in Article 2 (§ 38.2-101 et seq.) of Chapter 1 of this title, to insure a private pleasure watercraft.

In this instance the term name is being flagged as the entirety of 

> "new or renewal policy or contract covering liability arising from the ownership, maintenance or use of a private pleasure watercraft" shall mean and include only a policy or contract of marine protection and indemnity insurance, as defined in subsection B of § 38.2-126, written as a separate policy, which is not in combination with any other class of insurance defined in Article 2 (§ 38.2-101 et seq.) of Chapter 1 of this title, to insure a private pleasure watercraft.

So: 

* [ ] Add `shall mean` and `shall mean and include` to the list of `$linking_phrases`.
* [ ] Expand `term` to 255 characters (up from 128) to handle the 133 here.

**Comment by waldoj** [comment]
Wow. It's really edge cases all the way down.
