### ISSUE TITLE
Some former arrays are now objects, leading to errors

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#708]
Having turned some arrays into objects, attempts to access them as arrays are yielding fatal errors.

**Comment by krues8dr** [comment]
Can you tell me where this is happening?  In most cases I've done the opposite.

**Comment by krues8dr** [comment]
>waldoj self-assigned this a minute ago

Or just have at it! :)

**Comment by waldoj** [comment]
I'm in the midst of a building up a pull request. :)

**Comment by krues8dr** [comment]
If #710 doesn't fix all the errors you're seeing, please paste them into the issue here so I can hunt them down.

**Comment by waldoj** [comment]
That did it!
