### ISSUE TITLE
Subsection link icon is always displayed

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#714]
![screen shot 2017-04-22 at 9 09 09 pm](https://cloud.githubusercontent.com/assets/656758/25309624/0adbeaba-27a0-11e7-98ef-cdd7c0b77458.png)

These are only supposed to be displayed on hover, to avoid cluttering up the display of text. (It's showing up on a new line in this screenshot due to text padding in the XSLT for Virginia, AFAIK—that's not a State Decoded bug.) Restore that functionality.

**Comment by krues8dr** [comment]
I removed this because there's no such thing as hover on phones/tablets. :)

**Comment by waldoj** [comment]
It looks really bad. Since we're already using Modernizr, we can use `if (Modernizr.touch){}` to always display link icons on mobile devices, and only display them on hover on the desktop. Does that seem like a good solution?

(For reference, 42% of Virginia Decoded traffic comes from phones, and 4% from tablets. So about half of all visits are on touch devices.)

**Comment by krues8dr** [comment]
I cannot find a reference, but I think we'd talked about getting rid of ZeroClipboard a long while back (and I thought I'd already done this) – but lo, here it is again.  The thinking here was that most users know how to copy a link by now, and the use case is relatively narrow.  We were going to keep the icons, however.  LMK if that sounds familiar and I'll (re-)do that as well.

**Comment by krues8dr** [comment]
Ah yes, and this was made more complicated as a result of the paragraph tags coming from the XML now – meaning the permalinks are _adjacent_ to the `P`s, not _inside_.  Let's see if I can't remember how to get sibling selector hovers to work properly.

**Comment by krues8dr** [comment]
Touch events may also be available in laptops and desktops that have a touch screen, which are increasingly common.  Just something to keep in mind, not a dealbreaker here.  Also IE-powered devices do not use touch events, so they won't get these links.  I assume windows phone users are a very tiny % of our users though.

**Comment by krues8dr** [comment]
Another reason to kill Zero Clipboard is the very obvious one that Flash is dead anyway.
