### ISSUE TITLE
WOFF, TTF requests are being rewritten

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#716]
Requests for the WOFF, WOFF 2.0, and TTF files in the Font Awesome distribution (e.g., `fontawesome-webfont.woff2`) are being rewritten to an invalid URL, resulting in the query yielding a 404. For example, requests for:

`http://beta.vacode.org/themes/StateDecoded2013/static/fonts/font-awesome/fontawesome-webfont.woff2?v=4.7.0`

are rewritten as:

`http://beta.vacode.org/themes/StateDecoded2013/static/fonts/font-awesome/fontawesome-webfont.woff2/?v=4.7.0`

(Note the additional `/` after `.woff2`.) Fix this to make sure that these fonts transfer properly.

**Comment by krues8dr** [comment]
This rule should have caught it: `RewriteCond %{REQUEST_URI} !themes/(.+)/static/(.+)$` which led me to discover that the Font Awesome paths were pointing at the wrong directory.  Easily resolved.
