### ISSUE TITLE
Restore dictionary definition functionality

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#717]
Hovering over a defined term no longer yields a definition. This functionality requires that the law ID be exposed to the JavaScript API. That was eliminated in commit cdbc2e7db2928716c40d0b7524b7cf3453824c8e. This line needs to be restored to `law.php`:

```php
$content->append('javascript', "var law_id = '" . $laws[0]->law_id . "';");
```

**Comment by krues8dr** [comment]
Ooh I have a shiny idea for this.

**Comment by krues8dr** [comment]
That'll do it. 

>Instead of using a global law_id and edition_id, we bolt this data onto the law's container article, then just ascend the tree when we need to look this information up.
