### ISSUE TITLE
Keyboard guide no longer works

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#718]
In the sidebar of each law page, there's a keyboard guide link. That used to display an overlay that would provide the keyboard shortcuts for navigation. That no longer does anything. I'm not sure why.

**Comment by krues8dr** [comment]
I *think* I fixed this earlier today: 792efda77da19c313cd3fe95dc51685430f6b8b1

**Comment by waldoj** [comment]
Huh, yeah, I can see how that would have done it, but it didn't. :-/ I've got the current master deployed to the Virginia beta site, and [you can try it out](http://beta.vacode.org/6.2-2501/). I'm not sure what's failing, but I'm also exhausted, so ¯\\\_(ツ)\_/¯.

**Comment by krues8dr** [comment]
This is a side effect of #717 breaking the JS on the page.  Once I resolved that this worked again.  Feel free to reopen if it doesn't, again.

**Comment by krues8dr** [comment]
E.g. works fine on pages without definitions: http://beta.vacode.org/6.2-2505/
