### ISSUE TITLE
Chicago Decoded Revival

### ISSUE THREAD

**Issue by zbhoy** [statedecoded/statedecoded#731]
Hi there,

I use the Chicago Decoded website and i have been seeing the banner that says it is no longer maintained. I would love to help maintain it and keep it up to date if that is an option.

**Comment by krusynth** [comment]
Sorry, but this is the project that Chicago Decoded is forked from, you should open an issue in [that repo instead](https://github.com/opengovfoundation/chicagocode). We are not directly affiliated with that site.
