### ISSUE TITLE
All-caps terms aren't always acronyms

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#89]
`Dictionary::define_term()` lowercases all passed words, except those words that are in all caps. Those are assumed to be acronyms, and kept in all caps. But it turns out that sometimes there really are defined words in all caps, such as in those codes that capitalize section headers. These need to be retrieved properly; right now, the term is underlined, but a mouseover reveals no definition.

**Comment by waldoj** [comment]
I'm two weeks into being too tired to understand how you did this. :) I don't think I ever devised, conceptually, a good solution to this problem. Mind giving me a paragraph-long explanation?

**Comment by krues8dr** [comment]
TLDR, I just rearranged it so that it searches for the term exactly as given first (e.g. `Abcd` -> `Abcd`), and if that fails, it tries to look for a lowercased version of the term (`Abcd` -> `abcd`), and then finally searches the global terms.  That seems to work as expected for my tests.

**Comment by waldoj** [comment]
Oh, great! :)

**Comment by krues8dr** [comment]
Is that close to what you were thinking?

**Comment by waldoj** [comment]
I wasn't thinking anything—I don't believe I'd thought through _how_ to solve it. :)

**Comment by krues8dr** [comment]
This seems to work for things like terms that are capitalized at the beginning of sentences, or otherwise weird.  Preserves proper names as expected.  There could be some edge-cases I've missed, so if you've got specific examples I can tweak.
